- hosts: master
  name: "Setup home server"
  remote_user: pi
  vars:
    pkgstoinstall: [ libffi-dev, libssl-dev, python3, python3-pip,  git, build-essential, locales-all, cmake, libuv1-dev, libssl-dev,libhwloc-dev  ]
  become: yes
  roles:
    - update
    - docker
    - fans
    - portainer
    - adguard
    - bitwarden
    - uptime-kuma