version: '3.2'
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 9999:9999/tcp
    volumes:
      - /data/adguard/work:/opt/adguardhome/work
      - /data/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
