version: '3.2'

services:
  agent:
    image: portainer/agent:2.11.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.11.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify --sslcert /run/secrets/portainer.sslcert --sslkey /run/secrets/portainer.sslkey
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    secrets:
        - portainer.sslcert
        - portainer.sslkey

volumes:
  portainer_data:
    external: true

networks:
  portainer:
    driver: overlay
    attachable: true

secrets:
  portainer.sslcert:
    external: true
  portainer.sslkey:
    external: true
