version: '3.7'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    networks:
      monitoring_network:
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
         condition: on-failure

volumes:
  uptime-kuma:
    external: true
    
networks:
  monitoring_network:
    driver: overlay
    external: true
